# Generated by Django 4.2.2 on 2023-06-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
    ]
